<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="AllureSuitre" duration-ms="3108" started-at="2020-09-30T18:36:16Z" finished-at="2020-09-30T18:36:19Z">
    <groups>
    </groups>
    <test name="AllureTest " duration-ms="3108" started-at="2020-09-30T18:36:16Z" finished-at="2020-09-30T18:36:19Z">
      <class name="alluretestcase.Appointmenttestcase">
        <test-method status="PASS" signature="launchbrowser()[pri:0, instance:alluretestcase.Appointmenttestcase@6bab2585]" name="launchbrowser" is-config="true" duration-ms="9025" started-at="2020-09-30T14:36:07Z" finished-at="2020-09-30T14:36:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchbrowser -->
        <test-method status="FAIL" signature="table()[pri:0, instance:alluretestcase.Appointmenttestcase@6bab2585]" name="table" duration-ms="2638" started-at="2020-09-30T14:36:16Z" finished-at="2020-09-30T14:36:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Dermatology Details] but found [Dermatology]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Dermatology Details] but found [Dermatology]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at alluretestcase.Appointmenttestcase.table(Appointmenttestcase.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- table -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:alluretestcase.Appointmenttestcase@6bab2585]" name="teardown" is-config="true" duration-ms="0" started-at="2020-09-30T14:36:19Z" finished-at="2020-09-30T14:36:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- alluretestcase.Appointmenttestcase -->
    </test> <!-- AllureTest  -->
  </suite> <!-- AllureSuitre -->
</testng-results>
